### PR TITLE
Add missing boxart

### PR DESCRIPTION
**Pull request by TheXpertXD**
Brings in 56 new box art thumbnails for the PlayStation Portable.

### CODE REVIEW

**Comment by TheXpertXD** [comment]
> 
> 
> These look great! Thanks a lot....
> 
> Would you mind ensuring the images are a max-width of 512px?

Sure can, will try to look over it tonight and I'll be sure to fix up anything not making the cut

**Comment by TheXpertXD** [comment]
Finally got around to resizing everything, all 512 px wide or less now 👍

**Comment by TheXpertXD** [comment]
That brings the new total of new arts to around 60

**Comment by RobLoach** [comment]
Nicely done! Looks great!

**Pull request merged**
